import type { TypeManifest, TypeDeclaration } from "./types";
import { convertType } from "./convert";

function selfName(decl: TypeDeclaration): string {
    if (decl.typeParams.length === 0) return decl.name;
    return `${decl.name}<${decl.typeParams.join(", ")}>`;
}

function emitMember(
    memberName: string,
    memberType: string,
    optional: boolean,
    parentDecl: TypeDeclaration,
    // empty set = no __luauAnnotateTypes. prefix (we're inside the generated file)
    knownTypes: Set<string>,
): string {
    const optSuffix = optional ? "?" : "";

    // Method type: stored as TS `(params) => ret` — convert to Luau with self injected
    if (memberType.includes("=>")) {
        const arrowIdx = memberType.lastIndexOf("=>");
        const rawParams = memberType.slice(1, memberType.lastIndexOf(")", arrowIdx)).trim();
        const rawRet = memberType.slice(arrowIdx + 2).trim();

        const self = `self: ${selfName(parentDecl)}`;
        const paramStr = rawParams
            ? rawParams
                .split(",")
                .map((p) => {
                    const trimmed = p.trim();
                    const colonIdx = trimmed.indexOf(":");
                    if (colonIdx === -1) return convertType(trimmed, knownTypes);
                    const pName = trimmed
                        .slice(0, colonIdx)
                        .replace(/^\.\.\./, "")
                        .trim();
                    const pType = convertType(trimmed.slice(colonIdx + 1).trim(), knownTypes);
                    return `${pName}: ${pType}`;
                })
                .join(", ")
            : "";

        const luauRet = rawRet === "void" ? "()" : convertType(rawRet, knownTypes);
        const fullParams = paramStr ? `${self}, ${paramStr}` : self;
        return `    ${memberName}: (${fullParams}) -> ${luauRet}${optSuffix},`;
    }

    // Property type
    const luauType = convertType(memberType, knownTypes);
    return `    ${memberName}: ${luauType}${optSuffix},`;
}

function emitTypeDecl(decl: TypeDeclaration, knownTypes: Set<string>): string {
    const typeParams = decl.typeParams.length > 0 ? `<${decl.typeParams.join(", ")}>` : "";
    const lines = [`export type ${decl.name}${typeParams} = {`];
    for (const member of decl.members) {
        lines.push(emitMember(member.name, member.type, member.optional, decl, knownTypes));
    }
    lines.push("}");
    return lines.join("\n");
}

export function generateTypesFile(manifests: TypeManifest[]): string {
    const allTypes = new Map<string, TypeDeclaration>();
    for (const manifest of manifests) {
        for (const [, decl] of Object.entries(manifest.types)) {
            allTypes.set(decl.name, decl);
        }
    }
    if (allTypes.size === 0) return "";

    // Inside the generated file, types reference each other by bare name — no prefix
    const localTypes = new Set(allTypes.keys());

    const lines = ["-- [generated by lumine — do not edit]", ""];
    for (const decl of allTypes.values()) {
        lines.push(emitTypeDecl(decl, localTypes));
        lines.push("");
    }
    lines.push("return {}");
    return lines.join("\n");
}
