/**
 * emit.ts
 *
 * Converts TypeManifest type declarations into Luau source strings for
 * inline injection into .luau files. Works entirely on LuauType AST nodes —
 * no string parsing, no regex, no split(",").
 *
 * Also owns the Lumine.lua builtin file generation.
 */
import type { TypeManifest, TypeDecl } from "./types";
import { printLuauType, mkRef, type LuauType, type LuauFnParam } from "./luau-types";
import { LUMINE_BUILTIN_FUNCTIONS } from "./builtins";

// ── Type declaration emitter ──────────────────────────────────────────────────

/**
 * Print a single type declaration as a Luau `export type` statement.
 * Interface table types with `isMethod` fields get `self` injected.
 */
function emitTypeDecl(decl: TypeDecl): string {
	const params = decl.typeParams.length ? `<${decl.typeParams.join(", ")}>` : "";
	const selfType = decl.typeParams.length
		? mkRef(
				decl.name,
				decl.typeParams.map((p) => mkRef(p)),
			)
		: mkRef(decl.name);

	const body = emitTypeBody(decl.body, selfType);
	return `export type ${decl.name}${params} = ${body}`;
}

/**
 * Recursively print a LuauType body. For table types, handles method members
 * by injecting `self: SelfType` as the first parameter — this cannot be done
 * inside printLuauType because only declaration-level tables have a self type.
 */
function emitTypeBody(t: LuauType, selfType: LuauType): string {
	if (t.kind !== "table") return printLuauType(t);

	const lines: string[] = [];

	if (t.indexer) {
		lines.push(
			`    [${printLuauType(t.indexer.key, 0, true)}]: ${printLuauType(t.indexer.value, 0, true)},`,
		);
	}

	for (const f of t.fields) {
		const opt = f.optional ? "?" : "";
		if (f.isMethod && f.type.kind === "function") {
			// Inject self as first param
			const selfParam: LuauFnParam = {
				name: "self",
				type: selfType,
				optional: false,
				rest: false,
			};
			const withSelf: LuauType = {
				kind: "function",
				params: [selfParam, ...f.type.params],
				returns: f.type.returns,
			};
			lines.push(`    ${f.name}: ${printLuauType(withSelf)}${opt},`);
		} else {
			lines.push(`    ${f.name}: ${printLuauType(f.type, 0, true)}${opt},`);
		}
	}

	if (lines.length === 0) return "{}";
	return `{\n${lines.join("\n")}\n}`;
}

// ── Per-file inline type declarations ────────────────────────────────────────

/**
 * Generate all `export type` declarations for types defined in this manifest.
 * Used to inline types directly into the corresponding .luau file.
 *
 * Deduplicates namespace types (registered under both "Ns.Foo" and "Ns_Foo").
 */
export function generateInlineTypeDecls(manifest: TypeManifest): string {
	const seen = new Set<string>();
	const lines: string[] = [];

	for (const decl of Object.values(manifest.types)) {
		if (seen.has(decl.name)) continue;
		seen.add(decl.name);
		lines.push(emitTypeDecl(decl));
		lines.push("");
	}

	return lines.join("\n").trimEnd();
}

// ── Lumine.lua builtin file ───────────────────────────────────────────────────

/**
 * Generate the full content of Lumine.lua — the file placed next to
 * RuntimeLib and Promise in the roblox-ts include folder.
 * Contains Luau type function implementations for Partial, Required, etc.
 * and the structural Promise<T> type.
 */
export function generateLumineFile(): string {
	return `-- [generated by lumine — do not edit]\n\n${LUMINE_BUILTIN_FUNCTIONS}\nreturn {}\n`;
}
