/**
 * emit.ts
 *
 * Converts TypeManifest type declarations into Luau source strings.
 * Works entirely on LuauType AST nodes — no string parsing, no regex.
 *
 * Also owns the Lumine.lua builtin file generation.
 *
 * Note: generateInlineTypeDecls was removed in favour of _lumine_types.luau.
 * Per-file inline type injection is gone; all types now live in the per-directory
 * _lumine_types.luau generated by dirs.ts.
 */
import type { TypeDecl } from "./types";
import { printLuauType, mkRef, type LuauFnParam } from "./luau-types";
import { LUMINE_BUILTIN_FUNCTIONS } from "./builtins";

// ── Bare recursive type guard ─────────────────────────────────────────────────

/** True if typeName can be reached from body through only union/intersection/optional nodes. */
export function isBarelyRecursive(typeName: string, body: LuauType): boolean {
    switch (body.kind) {
        case "reference":
            return body.name === typeName && !body.args?.length;
        case "union":
        case "intersection":
            return body.members.some((m) => isBarelyRecursive(typeName, m));
        case "optional":
            return isBarelyRecursive(typeName, body.inner);
        default:
            return false;
    }
}

// ── Type declaration emitter ──────────────────────────────────────────────────

/**
 * Print a single type declaration as a Luau `export type` statement.
 * Interface table types with `isMethod` fields get `self` injected.
 */
export function emitTypeDecl(decl: TypeDecl): string {
    const params = decl.typeParams.length ? `<${decl.typeParams.join(", ")}>` : "";

    if (isBarelyRecursive(decl.name, decl.body)) {
        return `export type ${decl.name}${params} = any -- ⚠ bare recursive type`;
    }

    const selfType = decl.typeParams.length
        ? mkRef(
            decl.name,
            decl.typeParams.map((p) => mkRef(p)),
        )
        : mkRef(decl.name);

    const body = emitTypeBody(decl.body, selfType);
    return `export type ${decl.name}${params} = ${body}`;
}

/**
 * Recursively print a LuauType body. For table types, handles method members
 * by injecting `self: SelfType` as the first parameter — this cannot be done
 * inside printLuauType because only declaration-level tables have a self type.
 */
export function emitTypeBody(t: LuauType, selfType: LuauType): string {
    if (t.kind !== "table") return printLuauType(t);

    const lines: string[] = [];

    if (t.indexer) {
        lines.push(
            `    [${printLuauType(t.indexer.key, 0, true)}]: ${printLuauType(t.indexer.value, 0, true)},`,
        );
    }

    for (const f of t.fields) {
        const opt = f.optional ? "?" : "";
        if (f.isMethod && f.type.kind === "function") {
            // Inject self as first param
            const selfParam: LuauFnParam = {
                name: "self",
                type: selfType,
                optional: false,
                rest: false,
            };
            const withSelf: LuauType = {
                kind: "function",
                params: [selfParam, ...f.type.params],
                returns: f.type.returns,
            };
            lines.push(`    ${f.name}: ${printLuauType(withSelf)}${opt},`);
        } else {
            lines.push(`    ${f.name}: ${printLuauType(f.type, 0, true)}${opt},`);
        }
    }

    if (lines.length === 0) return "{}";
    return `{\n${lines.join("\n")}\n}`;
}

// ── Lumine.lua builtin file ───────────────────────────────────────────────────

/**
 * Generate the full content of Lumine.lua — the file placed next to
 * RuntimeLib and Promise in the roblox-ts include folder.
 * Contains Luau type function implementations for Partial, Required, etc.
 * and the structural Promise<T> type.
 */
export function generateLumineFile(): string {
    return `-- [generated by lumine — do not edit]\n\n${LUMINE_BUILTIN_FUNCTIONS}\nreturn {}\n`;
}
